Extend everest docker image with OCPP 2.0.1 compatibility (#129)
* Make build date a optional parameter: --build-date
* Add missing libevent-dev
* Add script to initialize OCPP 2.0.1 device model

This uses the init_device_model_db.py from libocpp and associated files, so copy over the libocpp/config/v201 directory into the resulting image as well

* Add --build-date option to README
* Add .gitignore for logs directory
* Add docker-compose.yml, sample configs for OCPP 2.0.1 and run script
* Add example nodered dockerfile
* Add admin panel ports
* Properly expose admin panel port
* Add --no-ssh parameter

This can remove the "--ssh default" parameter from docker build

* Add --container-runtime parameter

This makes the container runtime used for building and saving the image selectable
Defaults to "docker" but can be used to e.g. select "podman" as well

* Add --additional-cmake-parameters parameter

This allows additional CMake parameters to be passed to the EVerest build

* Add additional log output

This logs the build date, used container runtime and used additional CMake parameters

* Add trap for build error

* Log a error message if the OCPP 2.0.1 config directory could not be copied

* Update Dockerfile from debian 11 to debian 12

* Update readme

---------

Signed-off-by: Kai-Uwe Hermann <kai-uwe.hermann@pionix.de>

diff --git a/docker/everest-docker-image/Dockerfile b/docker/everest-docker-image/Dockerfile
--- a/docker/everest-docker-image/Dockerfile
+++ b/docker/everest-docker-image/Dockerfile
@@ -1,10 +1,11 @@
 # syntax=docker/dockerfile:1
-FROM debian:11 AS builder
+FROM debian:12-slim AS builder
 
 ARG REPO
 ARG BRANCH
 ARG EVEREST_CONFIG
 ARG OCPP_CONFIG
+ARG ADDITIONAL_CMAKE_PARAMETERS
 
 RUN apt-get update \
     && apt-get install --no-install-recommends -y \
@@ -20,7 +21,7 @@ RUN apt-get update \
     cppcheck \
     libboost-all-dev \
     maven \
-    openjdk-11-jdk \
+    openjdk-17-jdk \
     nodejs \
     npm \
     libsqlite3-dev \
@@ -29,6 +30,7 @@ RUN apt-get update \
     libcurl4-openssl-dev \
     libpcap-dev \
     libcap-dev \
+    python3-venv \
     && apt-get clean \
     && rm -rf /var/lib/apt/lists/*
 
@@ -43,7 +45,9 @@ RUN ssh-keyscan github.com > ~/.ssh/known_hosts
 
 RUN mkdir -p /workspace/everest/cpm_source_cache    
 ENV CPM_SOURCE_CACHE="/workspace/everest/cpm_source_cache"
-
+ENV EVEREST_VENV=/workspace/everest/venv
+RUN python3 -m venv ${EVEREST_VENV}
+ENV PATH="${EVEREST_VENV}/bin:${PATH}"
 RUN git clone https://github.com/EVerest/everest-cmake.git
 RUN git clone https://github.com/EVerest/everest-utils.git
 WORKDIR /workspace/everest/everest-utils/ev-dev-tools
@@ -54,6 +58,8 @@ WORKDIR /workspace/everest/everest-dev-environment/dependency_manager
 RUN python3 -m pip install .
 WORKDIR /workspace/everest
 RUN git clone https://github.com/EVerest/ext-switchev-iso15118.git
+WORKDIR /workspace/everest/ext-switchev-iso15118/
+RUN pip install -r requirements.txt
 
 WORKDIR /workspace/everest
 
@@ -65,9 +71,11 @@ RUN rm -rf "/workspace/everest/$(basename "${REPO}" .git)/build" && \
     git checkout "${BRANCH}" && \
     mkdir "/workspace/everest/$(basename "${REPO}" .git)/build" && \
     cd "/workspace/everest/$(basename "${REPO}" .git)/build" && \
-    cmake .. -DEVEREST_BUILD_ALL_MODULES=ON -DCMAKE_INSTALL_PREFIX=/opt/everest && \
+    cmake .. -DCMAKE_INSTALL_PREFIX=/opt/everest ${ADDITIONAL_CMAKE_PARAMETERS} && \
     make -j"$(nproc)" install
 
+# Try to copy the OCPP 2.0.1 config directory to have the init_device_model_db.py script available for (re-)initialization of the device model
+RUN cp -R "$(grep -m 1 "ocpp_SOURCE_DIR:STATIC=" "/workspace/everest/$(basename "${REPO}" .git)/build/CMakeCache.txt" | sed "s/ocpp_SOURCE_DIR:STATIC=//")/config/v201" /opt/everest/ocpp201config || echo "Could not copy OCPP 2.0.1 config directory"
 RUN mkdir -p /opt/everest/config/user-config
 COPY "${EVEREST_CONFIG}" /opt/everest/config/
 COPY "${OCPP_CONFIG}" /opt/everest/config/
@@ -77,11 +85,11 @@ RUN if [ "${OCPP_CONFIG}" != "ocpp-config.json" ]; then mv /opt/everest/config/"
 COPY logging.ini /opt/everest/config
 
 # syntax=docker/dockerfile:1
-FROM debian:11-slim
+FROM debian:12-slim
 
 RUN apt-get update \
     && apt-get install --no-install-recommends -y \
-    openjdk-11-jre \
+    openjdk-17-jre \
     nodejs \
     npm \
     python3-pip \
@@ -90,17 +98,22 @@ RUN apt-get update \
     libboost-log1.74.0 \
     libboost-chrono1.74.0 \
     libboost-system1.74.0 \
-    libssl1.1 \
+    libssl3 \
     libcurl4 \
     libcap2 \
     less \
+    libevent-dev \
+    python3-venv \
     && apt-get clean \
     && rm -rf /var/lib/apt/lists/*
 
-COPY --from=builder /workspace/everest/ext-switchev-iso15118/requirements.txt ./
-RUN pip install --user -r requirements.txt
+ENV EVEREST_VENV=/workspace/everest/venv
+RUN python3 -m venv ${EVEREST_VENV}
+ENV PATH="${EVEREST_VENV}/bin:${PATH}"
+COPY --from=builder /workspace/everest/venv /workspace/everest/venv
 
 WORKDIR /opt/everest
 COPY --from=builder /opt/everest ./
+COPY ./scripts/initialize.sh /opt/everest
 
 CMD [ "/opt/everest/bin/manager", "--conf", "/opt/everest/config/config.yaml" ]
